<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #1e293b; font-size: 10px; }
        h1 { margin: 0 0 4px; color: #17365d; font-size: 18px; }
        .school { font-size: 13px; font-weight: bold; color: #0f172a; }
        .meta { width: 100%; margin: 12px 0; border-collapse: collapse; }
        .meta td { padding: 2px 6px 2px 0; vertical-align: top; }
        .meta .label { width: 125px; font-weight: bold; color: #475569; }
        .report { width: 100%; border-collapse: collapse; }
        .report th { background: #1e3a5f; color: white; padding: 6px; border: 1px solid #cbd5e1; }
        .report td { padding: 5px; border: 1px solid #cbd5e1; }
        .report tr:nth-child(even) td { background: #f8fafc; }
        .totals { margin-top: 14px; }
        .totals span { display: inline-block; margin-right: 14px; }
        .footer { margin-top: 18px; color: #64748b; font-size: 8px; }
    </style>
</head>
<body>
    @if(!empty($meta['__logo']) && is_file($meta['__logo']))
        <img src="{{ $meta['__logo'] }}" alt="School logo" style="float:right;width:58px;height:58px;object-fit:contain">
    @endif
    <div class="school">{{ $meta['School Name'] }}</div>
    <h1>{{ $meta['Report Title'] }}</h1>
    <table class="meta">
        @foreach($meta as $label => $value)
            @continue(in_array($label, ['__logo', 'School Name', 'Report Title']))
            <tr><td class="label">{{ $label }}</td><td>{{ $value }}</td></tr>
        @endforeach
    </table>
    <table class="report">
        <thead><tr>@foreach($headings as $heading)<th>{{ $heading }}</th>@endforeach</tr></thead>
        <tbody>
        @foreach($rows as $row)
            <tr>@foreach($row as $cell)<td>{{ $cell }}</td>@endforeach</tr>
        @endforeach
        </tbody>
    </table>
    <div class="totals">
        <strong>Status totals:</strong>
        @foreach($totals as $status => $count)<span>{{ $status }}: {{ $count }}</span>@endforeach
    </div>
    <div class="footer">Generated by the RFID Attendance and School Operations System.</div>
</body>
</html>
